# Generated by Django 3.2.6 on 2021-08-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Loqo')),
            ],
            options={
                'verbose_name': 'Şirkət',
                'verbose_name_plural': 'Bizimlə işləyən şirkətlər',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='Telefon nömrəsi')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Səhifə başlığı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Loqo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='İkon')),
                ('slogan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sloqan')),
                ('banner_title', models.CharField(max_length=250, verbose_name='Banner başlığı')),
                ('banner_description', models.TextField(verbose_name='Banner mətni')),
                ('banner_image', models.ImageField(upload_to='images/', verbose_name='Banner şəkli')),
                ('suggestion_description', models.TextField(verbose_name='Təklif bölməsi izahı')),
                ('companies_description', models.TextField(verbose_name='Şirkətlər bölməsi izahı')),
                ('contact_image', models.ImageField(upload_to='images/', verbose_name='Form şəkli')),
                ('admin_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon nömrəsi')),
                ('admin_whatsapp_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Whatsapp nömrəsi')),
                ('corporative_email', models.EmailField(max_length=100, verbose_name='Korporativ email')),
            ],
            options={
                'verbose_name': 'Səhifə',
                'verbose_name_plural': 'Səhifə',
            },
        ),
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Məzmun')),
            ],
            options={
                'verbose_name': 'Xüsusiyyət',
                'verbose_name_plural': 'Sayt Xüsusiyyətləri',
            },
        ),
        migrations.CreateModel(
            name='PurposeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Məqsəd',
                'verbose_name_plural': 'Məqsədlərimiz',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlərimiz',
            },
        ),
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Təklif',
                'verbose_name_plural': 'Təkliflərimiz',
            },
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('branch_title', models.CharField(max_length=100, verbose_name='Peşə')),
            ],
            options={
                'verbose_name': 'Üzv',
                'verbose_name_plural': 'Komandamız',
            },
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('site_url', models.URLField()),
            ],
            options={
                'verbose_name': 'İş',
                'verbose_name_plural': 'İşlərimiz',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Bacarıq')),
                ('skill_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='page.teammodel')),
            ],
            options={
                'verbose_name': 'Bacarıq',
                'verbose_name_plural': 'Bacarıqlar',
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=50, verbose_name='Sosial media')),
                ('account_link', models.URLField(verbose_name='Hesab URL-i')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='page.teammodel')),
            ],
            options={
                'verbose_name': 'Hesab',
                'verbose_name_plural': 'Hesablar',
            },
        ),
    ]
