# Generated by Django 3.2.6 on 2021-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='corporative_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Korporativ email'),
        ),
    ]
