# Generated by Django 3.2.6 on 2021-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_suggestionmodel_suggestion_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Yeni'),
        ),
        migrations.AlterField(
            model_name='suggestionmodel',
            name='suggestion_direction',
            field=models.CharField(choices=[('L', 'Sol'), ('R', 'Sağ')], default='L', max_length=1, verbose_name='İstiqamət'),
        ),
    ]
