# Generated by Django 3.2.6 on 2021-08-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210823_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='image',
            field=models.ImageField(default='images/avatar-big.png', upload_to='images/'),
        ),
    ]
