# Generated by Django 3.2.6 on 2021-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_teammodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='admin_phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon nömrəsi'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='admin_whatsapp_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Whatsapp nömrəsi'),
        ),
    ]
