# Generated by Django 3.2.6 on 2021-08-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20210823_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='country_code',
            field=models.CharField(default='+994', max_length=8, verbose_name='Ölkə kodu'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='companies_description',
            field=models.TextField(blank=True, null=True, verbose_name='Şirkətlər bölməsi izahı'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='suggestion_description',
            field=models.TextField(blank=True, null=True, verbose_name='Təklif bölməsi izahı'),
        ),
    ]
