# Generated by Django 3.2.6 on 2021-08-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20210824_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=50, verbose_name='Sosial media')),
                ('account_link', models.URLField(max_length=250, verbose_name='Hesab linkləri')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_accounts', to='page.pagemodel', verbose_name='Səhifə')),
            ],
            options={
                'verbose_name': 'Hesab',
                'verbose_name_plural': 'Sosial media hesabları',
            },
        ),
    ]
