# Generated by Django 3.2.6 on 2021-08-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_pageaccountsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodel',
            options={'verbose_name': 'Səhifə', 'verbose_name_plural': 'Əsas səhifə'},
        ),
    ]
