# Generated by Django 3.2.6 on 2021-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20210828_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Açar sözlər'),
        ),
    ]
