# Generated by Django 3.2.6 on 2021-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_contactmodel_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Baxış tarixi və saatı')),
            ],
            options={
                'verbose_name': 'Baxış',
                'verbose_name_plural': 'Baxışlar',
            },
        ),
    ]
