# Generated by Django 3.2.6 on 2021-11-01 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_pageview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='view_date_time',
        ),
        migrations.AddField(
            model_name='pageview',
            name='view_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Baxış tarixi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageview',
            name='view_month',
            field=models.IntegerField(default=0, verbose_name='Baxış ayı'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='view_year',
            field=models.IntegerField(default=0, verbose_name='Baxış ili'),
        ),
    ]
